"""add active restaurant

Revision ID: 5280260b89fd
Revises: 4eceaece4c7c
Create Date: 2020-07-18 15:46:36.163418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5280260b89fd'
down_revision = '4eceaece4c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'active')
    # ### end Alembic commands ###
